# Generated by Django 3.2 on 2022-01-11 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='documents/%Y-%m-%d/%H-%m-%S')),
                ('status', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_of_words', models.CharField(max_length=100)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('file_link', models.CharField(max_length=500)),
                ('batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.batch')),
            ],
        ),
    ]
