name: Deploy to Amazon EKS
on:
  push:
    branches:
      - graphql
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: curie
          IMAGE_TAG: waterlabscurie_develop
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:waterlabscurie_develop --build-arg PORT=${{ secrets.PORT }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:waterlabscurie_develop
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:waterlabscurie_develop"

